image: golang:1.8

stages:
- test
- build
- push

variables:
  VERSION: $CI_BUILD_TAG

before_script:
- echo $PWD
- source script/prepare
- make prepare
- make validate
- make test || true

build:
  stage: build
  script:
  - make binary
  - make crossbinary
  artifacts:
    paths:
    - dist/

package:
  stage: build
  script:
  - tar cfz gorcon-arma-${VERSION}.src.tar.gz --exclude-vcs dist
  - cp config.json dist/
  - cp schedule.json dist/
  - cp README.md dist/
  - make install
  - VERSION=$VERSION make package
  - cp gorcon-arma-${VERSION}.src.tar.gz dist/
  - cp /go/gorcon-arma_${VERSION}.deb dist/
  environment:
    name: storage
    url: https://storage.play-net.org/minio/gorcon-arma
  artifacts:
    paths:
    - dist/

push:
  stage: push
  image: python:latest
  script:
  - pip install awscli
  - aws --endpoint-url https://storage.play-net.org s3 cp ./dist/ s3://gorcon-arma/artifacts --recursive --include "*"
  - curl -T dist/gorcon-arma_${VERSION}.deb -ufinch:$BINTRAY_API https://api.bintray.com/content/playnet/debian/GoRcon-ArmA/$VERSION/gorcon-arma-${VERSION}.deb
  only:
  - tags
  when: on_success
  environment:
    name: storage
    url: https://storage.play-net.org/minio/gorcon-arma
  artifacts:
    paths:
    - dist/