image: golang:1.8

stages:
- test
- build
- push

variables:
  VERSION: $CI_BUILD_TAG

before_script:
- echo $PWD
- source script/prepare
- make prepare
- make validate
- make test || true
build:
  stage: build
  script:
  - make binary
  - make crossbinary
  - cp config.json dist/
  - cp schedule.json dist/
  - cp README.md dist/
  - tar cfz gorcon-arma-${VERSION}.src.tar.gz --exclude-vcs dist
  artifacts:
    paths:
    - dist/

package:
  stage: build
  script:
  - make install
  - VERSION=$VERSION make package || true
  - cp /go/gorcon-arma_${VERSION}.deb . || true
  only:
  - tags
  environment:
    name: storage
    url: https://storage.play-net.org/minio/gorcon-arma
  artifacts:
    paths:
    - gorcon-arma_${VERSION}.deb

push:
  stage: push
  image: python:latest
  before_script:
  - pip install awscli
  - cp gorcon-arma_${VERSION}.deb dist/ || true
  script:
  - >-
    curl -X POST 
    -H 'Content-Type: application/json' 
    -d "{"version": \"${VERSION}\"}"
    https://sentry.play-net.org/api/hooks/release/builtin/2/7f8e5541d285e227b62d961abd34d0c3195f17f5a1081de5ff5edb1a12d60cb2/
  - aws --endpoint-url https://storage.play-net.org s3 cp ./dist/ s3://gorcon-arma/artifacts/${VERSION} --recursive --include "*"
  - curl -T gorcon-arma_${VERSION}.deb -ufinch:$BINTRAY_API https://api.bintray.com/content/playnet/debian/GoRcon-ArmA/$VERSION/gorcon-arma-${VERSION}.deb || true
  only:
  - tags
  when: on_success
  artifacts:
    paths:
    - dist/