image: golang:1.8

stages:
- test
- build
- push

variables:
  VERSION: $CI_BUILD_TAG

before_script:
- echo $PWD
- source script/prepare
- make prepare
- make validate
- make test || true

build:
  stage: build
  script:
  - make binary
  - make crossbinary
  artifacts:
    paths:
    - dist/

packagePush:
  stage: push
  before_script:
  - source script/prepare
  - make prepare
  - cp config.json dist/
  - cp schedule.json dist/
  - tar cfz gorcon-arma-${VERSION}.src.tar.gz --exclude-vcs --exclude dist
  - make install
  - VERSION=$VERSION make package
  - cp /go/gorcon-arma_${VERSION}.deb dist/
  script:
  - curl -T dist/gorcon-arma_${VERSION}.deb -ufinch:$BINTRAY_API https://api.bintray.com/content/playnet/debian/GoRcon-ArmA/$VERSION/gorcon-arma-${VERSION}.deb
  - curl -T gorcon-arma-${VERSION}.src.tar.gz -ufinch:$BINTRAY_API https://api.bintray.com/content/playnet/tarballs/GoRcon-ArmA/$VERSION/gorcon-arma-${VERSION}.src.tar.gz
  only:
  - tags
  when: on_success
  artifacts:
    paths:
    - dist/