language: go
go:
- 1.8
- 1.9
go_import_path: github.com/playnet-public/gorcon-arma
env:
  global:
  - REPO: $TRAVIS_REPO_SLUG
  - VERSION: $TRAVIS_TAG
install:
- make check
- make test || true
after_success:
- make build
- make crossbuild
- make install
before_deploy:
- tar cfz dist/gorcon-arma-${VERSION}.src.tar.gz --exclude-vcs --exclude dist .
deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: dist/gorcon-arma*
  skip_cleanup: true
  file_glob: true
  overwrite: true
  on:
    repo: playnet-public/gorcon-arma
    tags: true
